spring.application.name=backend

# ==========================================
# LOCAL PROFILE
# ==========================================

spring.profiles.active=local
spring.config.import=optional:application-local.properties

# ==========================================
# DATABASE
# ==========================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SERVER
# ==========================================

server.port=${PORT:8080}

# ==========================================
# CLOUDINARY
# ==========================================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ==========================================
# GEMINI
# ==========================================

gemini.api.key=${GEMINI_API_KEY}
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# ==========================================
# RAZORPAY
# ==========================================

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# ==========================================
# FILE UPLOAD
# ==========================================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
# ==========================================
# JWT
# ==========================================

jwt.secret=${JWT_SECRET}
